# Generated by Django 4.1 on 2024-04-12 05:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Note', '0003_alter_note_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
